### ISSUE TITLE
Crash when accessing the server via localhost

### ISSUE THREAD

**Issue by AlphaDE** [airthusiast/smart-friends-bridge#1]
When trying to list the devices as described I get for a SmartFriendsBox with                 shcVersion 2.21.7 and shApiVersion 2.20:

Nov  1 21:13:16 node: TypeError: Object.fromEntries is not a function
Nov  1 21:13:16 node:     at app.get (/home/pi/node_modules/smart-friends-bridge/controllers/WebController.js:42:27)
Nov  1 21:13:16 node:     at Layer.handle [as handle_request] (/home/pi/node_modules/express/lib/router/layer.js:95:5)
Nov  1 21:13:16 node:     at next (/home/pi/node_modules/express/lib/router/route.js:137:13)
Nov  1 21:13:16 node:     at Route.dispatch (/home/pi/node_modules/express/lib/router/route.js:112:3)
Nov  1 21:13:16 node:     at Layer.handle [as handle_request] (/home/pi/node_modules/express/lib/router/layer.js:95:5)
Nov  1 21:13:16 node:     at /home/pi/node_modules/express/lib/router/index.js:281:22
Nov  1 21:13:16 node:     at Function.process_params (/home/pi/node_modules/express/lib/router/index.js:335:12)
Nov  1 21:13:16 node:     at next (/home/pi/node_modules/express/lib/router/index.js:275:10)
Nov  1 21:13:16 node:     at expressit (/home/pi/node_modules/express/lib/middleware/init.js:40:5)
Nov  1 21:13:16 node:     at Layer.handle [as handle_request] (/home/pi/node_modules/express/lib/router/layer.js:95:5)

**Comment by AlphaDE** [comment]
A Node v10 issue (default with Raspbian), gone after updating to Node v14
